export const COLORS: any[] = 
[
    { "primary": "#F28B82", "secondary": "#F48FB1" },
    { "primary": "#D1A3D6", "secondary": "#B39DDB" },
    { "primary": "#9FA8DA", "secondary": "#B3E5FC" },
    { "primary": "#B3E5FC", "secondary": "#B2EBF2" },
    { "primary": "#B2DFDB", "secondary": "#C8E6C9" },
    { "primary": "#DCE775", "secondary": "#E6EE9C" },
    { "primary": "#FFF9C4", "secondary": "#FFECB3" },
    { "primary": "#FFE0B2", "secondary": "#FFCCBC" },
    { "primary": "#D7CCC8", "secondary": "#CFD8DC" },
    { "primary": "#F8BBD0", "secondary": "#E1BEE7" },
    { "primary": "#D1C4E9", "secondary": "#C5CAE9" },
    { "primary": "#BBDEFB", "secondary": "#B2EBF2" },
    { "primary": "#B2DFDB", "secondary": "#C8E6C9" },
    { "primary": "#E6EE9C", "secondary": "#F0F4C3" },
    { "primary": "#FFF59D", "secondary": "#FFE082" },
    { "primary": "#EF9A9A", "secondary": "#F48FB1" },
    { "primary": "#CE93D8", "secondary": "#B39DDB" },
    { "primary": "#9FA8DA", "secondary": "#90CAF9" },
    { "primary": "#81D4FA", "secondary": "#80DEEA" },
    { "primary": "#80CBC4", "secondary": "#A5D6A7" },
    { "primary": "#DCE775", "secondary": "#FFEB3B" },
    { "primary": "#FFEB3B", "secondary": "#FFE082" },
    { "primary": "#FFCC80", "secondary": "#FFAB91" },
    { "primary": "#BCAAA4", "secondary": "#B0BEC5" },
    { "primary": "#CFD8DC", "secondary": "#E1BEE7" },
    { "primary": "#C5CAE9", "secondary": "#90CAF9" },
    { "primary": "#81D4FA", "secondary": "#80DEEA" },
    { "primary": "#80CBC4", "secondary": "#C8E6C9" },
    { "primary": "#C5E1A5", "secondary": "#E6EE9C" },
    { "primary": "#FFD54F", "secondary": "#FFAB40" }
  ]
  